### Class demos

In [ ]:
# import numpy
import numpy as np

In [8]:
# Check functions and variables contained in a module
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',

In [98]:
# Create an array from a list
arr = np.array([1, 2, 3, 4, 5, 6])

# Check the class
print(type(arr))

# Check the shape
print(arr.shape)

<class 'numpy.ndarray'>
(6,)


In [99]:
# Another way to show 
arr.dtype, arr.size

(dtype('int32'), 6)

In [100]:
# 0-D
arr0 = np.array(1)
print(arr0) 

# 1-D
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1) 

# 2-D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2) 

# 3-D
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3) 

# Use ndim to verify the dimensions
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

1
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3


In [105]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
# arr4 = np.arange(12)
print(arr4)

# 1-D to 2-D
print(arr4.reshape(4, 3))

# 1-D to 3-D
print(arr4.reshape(2, 2, 3))

# This will return an error
#print(arr4.reshape(2, 3, 4))

# This is fine, -1 means "unknown" dimension, python will compute it for you.
print(arr4.reshape(2, 3, -1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [115]:
# Create some uniform arrays
a1 = np.zeros((2,2))
print(a1)

a2 = np.full((3,3), np.pi)
print(a2)

a3 = np.ones_like(a1)
print(a3)

a4 = np.zeros_like(a2)
print(a4)

a5 = np.random.randint(10,100,10)
a5.reshape(-1,5)

[[0. 0.]
 [0. 0.]]
[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]
[[1. 1.]
 [1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[57, 93, 99, 81, 61],
       [16, 20, 79, 10, 77]])

In [116]:
# create some ranges
a5 = np.arange(10)
print(a5)

# arange is left inclusive, right exclusive
a6 = np.arange(0,3,0.25)
print(a6)

# linearly spaced
a7 = np.linspace(10,100,10)
print(a7)

# log spaced
a8 = np.logspace(1,2,10)
print(a8)

[0 1 2 3 4 5 6 7 8 9]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25 2.5  2.75]
[ 10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [117]:
# indexing
print(arr2)
print(arr2[0,0])
print(arr2[0,-1])
print(arr2[-1,-1])

[[1 2 3]
 [4 5 6]]
1
3
6


In [126]:
# Make up an array
a = np.linspace(1,12,12).reshape(3,4)
print(a)

# integer array indexing: [0,2] and [1,0]
print(a[[0, 1], [2, 0]]) 

# integer array indexing: [0,2], [1,0], [-1,-1], and [2,2]
print(a[[0, 1, -1, 2], [2, 0, -1, 2]]) 

# one step more, change the array
# can you figure out way
b = [0, 1, 2]
print(a)
a[np.arange(3), b] += 100
print(a)


[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[3 5]
[ 3  5 12 11]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[101   2   3   4]
 [  5 106   7   8]
 [  9  10 111  12]]


In [127]:
# Make up an array
a = np.linspace(1,12,12).reshape(3,4)
print(a)

# Find the elements of a that are bigger than 5
index_b = a > 5
print(index_b)
print(a[index_b])

# or simply
print(a[a>5])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 6  7  8  9 10 11 12]
[ 6  7  8  9 10 11 12]


In [128]:
# Make up two arrays
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise operator; both produce the array
print(x + y)
print(np.add(x, y))

# Difference
print(x - y)
print(np.subtract(x, y))

# Product
print(x * y)
print(np.multiply(x, y))

# Division
print(x / y)
print(np.divide(x, y))

# Square root
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [129]:
# Make up two arrays
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[5,6],[7,8]])

# Make up two more arrays
y1 = np.array([9,10])
y2 = np.array([11, 12])

# Inner product of vectors
print(y1.dot(y2))
print(np.dot(y1, y2))

# Matrix / vector product
print(x1.dot(y1))
print(np.dot(x1, y1))

# Matrix / matrix product
print(x1.dot(x2))
print(np.dot(x1, x2))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [130]:
print(x1)
print(x1.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [133]:
x = np.linspace(1,12,12).reshape(4,3)

# Get the sum
print(np.sum(x))

# Get the sum along an axis, make sure you understand
print(np.sum(x, axis=0)) 
print(np.sum(x, axis=1)) 

# Get the max and min along an axis
print(np.amax(x)) 
print(np.amax(x, axis=0))

78.0
[22. 26. 30.]
[ 6. 15. 24. 33.]
12.0
[10. 11. 12.]


In [138]:
# 4*3 array
x = np.array([[0,0,0], [10,10,10], [20,20,20], [30,30,30]])
print(x)

# 1*3 array
v = np.array([0, 1, 2])
print(v)

# 4*3 and 1*3 is compatible
# Add v to each row of x using broadcasting
y = x + v 
print(y) 

# 3*1 and 1*3 is compatible
x = x[:,0]
x = x[:, np.newaxis]
print(x)
v = np.array([0, 1, 2])
print(v)
y = x + v  # Add v to each row of x using broadcasting
print(y) 

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0]
 [10]
 [20]
 [30]]
[0 1 2]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [139]:
# Joining 1-D arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr) 

# Joining 2-D arrays
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr) 

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [143]:
arr = np.hstack((arr1, arr2))
print(arr) 

arr = np.vstack((arr1, arr2))
print(arr) 

arr = np.dstack((arr1, arr2))
print(arr) 

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


###  In-class exercises

#### Exercise 1

In [4]:
import numpy as np
# Zhang Licong

arr = np.ones((5,5))
arr[1:4,1:4] = 99
arr[2,2] = -20
print(arr)

[[  1.   1.   1.   1.   1.]
 [  1.  99.  99.  99.   1.]
 [  1.  99. -20.  99.   1.]
 [  1.  99.  99.  99.   1.]
 [  1.   1.   1.   1.   1.]]


### Exercise 2

In [10]:
# Deng Weihao
import random

a3 = np.random.randint(30, 41, 10)
print(a3)


[38 40 35 40 38 38 35 33 34 31]


### Exercise 3

In [13]:
# Zhou Runqiu
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr[np.isnan(arr)] = -9999
print(arr)

[ 1.000e+00  2.000e+00  3.000e+00 -9.999e+03  5.000e+00  6.000e+00
  7.000e+00 -9.999e+03]


### Exercise 4

In [19]:
# Zhang ziyan
m = np.random.uniform(1,50,20)
print(m)
m[m > 30] = 30
m[m < 10] = 10
print(m)

[13.65848286 14.76829696 45.34183154 23.9262814  17.51618986 42.61265066
  1.28265756 32.08178878 41.19038768  9.42880907 34.55371452 13.53060024
 21.80060142  2.28937171  3.84482538 23.96350927 26.68950542 41.33630894
 41.27203467  6.81542417]
[13.65848286 14.76829696 30.         23.9262814  17.51618986 30.
 10.         30.         30.         10.         30.         13.53060024
 21.80060142 10.         10.         23.96350927 26.68950542 30.
 30.         10.        ]


### Exercise 5

In [20]:
# Zhang Bo
a = np.arange(20)
print(a)
a[a % 2 == 1] = -1
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


### Exercise 6

In [22]:
# Liang Shijing

x = np.random.randint(0,100,10)
y = np.random.randint(0,100,10)

x[x > y]

array([82, 97, 96, 60])

#### Below are from Lei

In [150]:
# Exercise #1
x = np.ones((5,5),dtype=np.int32)
x[1:4,1:4] = 99
x[2,2] = -20
print(x)


[[  1   1   1   1   1]
 [  1  99  99  99   1]
 [  1  99 -20  99   1]
 [  1  99  99  99   1]
 [  1   1   1   1   1]]


In [24]:
x = np.linspace(1,10,10)
print(x)
y = np.copy(x)
y[1] = -99
print(x)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [167]:
# Exercise #2
np.random.randint(30, 40, 10)


array([36, 37, 33, 32, 35, 31, 32, 30, 32, 30])

In [ ]:
#Exercise #3
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[np.isnan(a)] = -999
print(a)

In [173]:
# Exercise #4
x = np.random.uniform(1,50,20)
print(x)

x[np.where(x>30)]=30
print(x)


[25.28593048 25.07053252 20.56416506 12.50854026 33.40192612 23.18574798
 37.53348356  8.63884887 36.4805451  36.05312458 29.10673047 21.72050166
 33.93529784 44.70688149  2.42483692 21.1412395   3.85044083  8.66489245
 14.34641079  1.81541532]
[25.28593048 25.07053252 20.56416506 12.50854026 30.         23.18574798
 30.          8.63884887 30.         30.         29.10673047 21.72050166
 30.         30.          2.42483692 21.1412395   3.85044083  8.66489245
 14.34641079  1.81541532]


In [180]:
# Exercise #5
x = np.arange(20)
print(x)
x [x % 2 != 0] = -1
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0 -1  2 -1  4 -1  6 -1  8 -1 10 -1 12 -1 14 -1 16 -1 18 -1]


In [188]:
# Exercise #6
x = np.random.randint(10, size=10)
y = np.random.randint(10, size=10)
print(x)
print(y)

print(x[np.where(x>y)])



[3 3 6 5 7 4 6 4 0 6]
[1 1 7 1 3 5 8 7 8 4]
[3 3 5 7 6]


In [191]:
# Exercise #7
x = np.linspace(1,10,10)
print(x)
y = x
y[1] = -99
print(x)

x = np.linspace(1,10,10)
print(x)
y = np.copy(x)
y[1] = -99
print(x)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[  1. -99.   3.   4.   5.   6.   7.   8.   9.  10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
